import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Menu } from "./components/menu/menu";
import { IMenuItem } from "./components/menu/types";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const menu: IMenuItem[] = [
  {
    label: "Home",
    url: "/",
  },
  {
    label: "Dashboard",
    children: [{ label: "Traffic", url: "/dashboard/traffic" }],
  },
];
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full h-screen flex `}
      >
        <Menu menuList={menu}></Menu>
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
